FROM almalinux:8

ARG DATE="unknown"

WORKDIR /
ENTRYPOINT ["/usr/sbin/aaasvc"]

COPY aaasvc-0.99.0.${DATE}-1.el8.x86_64.rpm /tmp

RUN yum -y install nc procps-ng openssl && \
    yum -y localinstall /tmp/aaasvc-0.99.0.${DATE}-1.el8.x86_64.rpm && \
    yum -y clean all

RUN groupadd --gid 2048 choria && \
    useradd -c "Choria Orchestrator - choria.io" -m --uid 2048 --gid 2048 choria && \
    chown -R choria:choria /etc/aaasvc

ENV USER choria
USER choria
