flags_map:
  Version: github.com/choria-io/aaasvc/cmd.Version

foss:
  compile_targets:
    defaults:
      output: aaasvc-{{version}}-{{os}}-{{arch}}
      strip: true

    64bit_linux:
      os: linux
      arch: amd64

    aarch64_linux:
      os: linux
      arch: arm64

    ppc64le_linux:
      os: linux
      arch: ppc64le

  packages:
    defaults:
      name: aaasvc
      bindir: /usr/sbin
      etcdir: /etc/aaasvc
      release: 1

    docker:
      user: choria
      template: docker
      target_arch: x86_64
      binary: 64bit_linux

    el_64:
      dist: el
      template: el/generic
      target_arch: x86_64
      binary: 64bit_linux

    el_ppc64le:
      template: el/generic
      dist: el
      target_arch: ppc64le
      binary: ppc64le_linux

    el_aarch64:
      template: el/generic
      dist: el
      target_arch: aarch64
      binary: aarch64_linux
